/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as CalculadoraImcRouteImport } from './routes/calculadora-imc'
import { Route as CalculadoraPesoMetaRouteImport } from './routes/calculadora-peso-meta'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReembolsosRouteImport } from './routes/reembolsos'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated/achievements'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedChartsRouteImport } from './routes/_authenticated/charts'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedExportRouteImport } from './routes/_authenticated/export'
import { Route as AuthenticatedFastingRouteImport } from './routes/_authenticated/fasting'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated/goals'
import { Route as AuthenticatedHabitsRouteImport } from './routes/_authenticated/habits'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedImcRouteImport } from './routes/_authenticated/imc'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedMeasurementsRouteImport } from './routes/_authenticated/measurements'
import { Route as AuthenticatedMoreRouteImport } from './routes/_authenticated/more'
import { Route as AuthenticatedNutritionRouteImport } from './routes/_authenticated/nutrition'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStatisticsRouteImport } from './routes/_authenticated/statistics'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedWeeklySummaryRouteImport } from './routes/_authenticated/weekly-summary'
import { Route as GuiasIndexRouteImport } from './routes/guias/index'
import { Route as GuiasSlugRouteImport } from './routes/guias/$slug'
import { Route as AuthenticatedPricingIndexRouteImport } from './routes/_authenticated/pricing/index'
import { Route as AuthenticatedPricingSuccessRouteImport } from './routes/_authenticated/pricing/success'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraImcRoute = CalculadoraImcRouteImport.update({
  id: '/calculadora-imc',
  path: '/calculadora-imc',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraPesoMetaRoute = CalculadoraPesoMetaRouteImport.update({
  id: '/calculadora-peso-meta',
  path: '/calculadora-peso-meta',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReembolsosRoute = ReembolsosRouteImport.update({
  id: '/reembolsos',
  path: '/reembolsos',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChartsRoute = AuthenticatedChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/dashboard.lazy').then((d) => d.Route),
)
const AuthenticatedExportRoute = AuthenticatedExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFastingRoute = AuthenticatedFastingRouteImport.update({
  id: '/fasting',
  path: '/fasting',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHabitsRoute = AuthenticatedHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedImcRoute = AuthenticatedImcRouteImport.update({
  id: '/imc',
  path: '/imc',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeasurementsRoute =
  AuthenticatedMeasurementsRouteImport.update({
    id: '/measurements',
    path: '/measurements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMoreRoute = AuthenticatedMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNutritionRoute = AuthenticatedNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStatisticsRoute = AuthenticatedStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWeeklySummaryRoute =
  AuthenticatedWeeklySummaryRouteImport.update({
    id: '/weekly-summary',
    path: '/weekly-summary',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const GuiasIndexRoute = GuiasIndexRouteImport.update({
  id: '/guias/',
  path: '/guias/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiasSlugRoute = GuiasSlugRouteImport.update({
  id: '/guias/$slug',
  path: '/guias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPricingIndexRoute =
  AuthenticatedPricingIndexRouteImport.update({
    id: '/pricing/',
    path: '/pricing/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPricingSuccessRoute =
  AuthenticatedPricingSuccessRouteImport.update({
    id: '/pricing/success',
    path: '/pricing/success',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculadora-imc': typeof CalculadoraImcRoute
  '/calculadora-peso-meta': typeof CalculadoraPesoMetaRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reembolsos': typeof ReembolsosRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terminos': typeof TerminosRoute
  '/welcome': typeof WelcomeRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/charts': typeof AuthenticatedChartsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/export': typeof AuthenticatedExportRoute
  '/fasting': typeof AuthenticatedFastingRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/imc': typeof AuthenticatedImcRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/measurements': typeof AuthenticatedMeasurementsRoute
  '/more': typeof AuthenticatedMoreRoute
  '/nutrition': typeof AuthenticatedNutritionRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/statistics': typeof AuthenticatedStatisticsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/weekly-summary': typeof AuthenticatedWeeklySummaryRoute
  '/guias/$slug': typeof GuiasSlugRoute
  '/guias/': typeof GuiasIndexRoute
  '/pricing/success': typeof AuthenticatedPricingSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/pricing/': typeof AuthenticatedPricingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculadora-imc': typeof CalculadoraImcRoute
  '/calculadora-peso-meta': typeof CalculadoraPesoMetaRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reembolsos': typeof ReembolsosRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terminos': typeof TerminosRoute
  '/welcome': typeof WelcomeRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/charts': typeof AuthenticatedChartsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/export': typeof AuthenticatedExportRoute
  '/fasting': typeof AuthenticatedFastingRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/imc': typeof AuthenticatedImcRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/measurements': typeof AuthenticatedMeasurementsRoute
  '/more': typeof AuthenticatedMoreRoute
  '/nutrition': typeof AuthenticatedNutritionRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/statistics': typeof AuthenticatedStatisticsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/weekly-summary': typeof AuthenticatedWeeklySummaryRoute
  '/guias/$slug': typeof GuiasSlugRoute
  '/guias': typeof GuiasIndexRoute
  '/pricing/success': typeof AuthenticatedPricingSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/pricing': typeof AuthenticatedPricingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/calculadora-imc': typeof CalculadoraImcRoute
  '/calculadora-peso-meta': typeof CalculadoraPesoMetaRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reembolsos': typeof ReembolsosRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terminos': typeof TerminosRoute
  '/welcome': typeof WelcomeRoute
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/charts': typeof AuthenticatedChartsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/export': typeof AuthenticatedExportRoute
  '/_authenticated/fasting': typeof AuthenticatedFastingRoute
  '/_authenticated/goals': typeof AuthenticatedGoalsRoute
  '/_authenticated/habits': typeof AuthenticatedHabitsRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/imc': typeof AuthenticatedImcRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/measurements': typeof AuthenticatedMeasurementsRoute
  '/_authenticated/more': typeof AuthenticatedMoreRoute
  '/_authenticated/nutrition': typeof AuthenticatedNutritionRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/statistics': typeof AuthenticatedStatisticsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/weekly-summary': typeof AuthenticatedWeeklySummaryRoute
  '/guias/$slug': typeof GuiasSlugRoute
  '/guias/': typeof GuiasIndexRoute
  '/_authenticated/pricing/success': typeof AuthenticatedPricingSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/pricing/': typeof AuthenticatedPricingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculadora-imc'
    | '/calculadora-peso-meta'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reembolsos'
    | '/register'
    | '/reset-password'
    | '/terminos'
    | '/welcome'
    | '/achievements'
    | '/activity'
    | '/calendar'
    | '/charts'
    | '/dashboard'
    | '/export'
    | '/fasting'
    | '/goals'
    | '/habits'
    | '/history'
    | '/imc'
    | '/insights'
    | '/measurements'
    | '/more'
    | '/nutrition'
    | '/profile'
    | '/settings'
    | '/statistics'
    | '/support'
    | '/weekly-summary'
    | '/guias/$slug'
    | '/guias/'
    | '/pricing/success'
    | '/api/auth/$'
    | '/pricing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculadora-imc'
    | '/calculadora-peso-meta'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reembolsos'
    | '/register'
    | '/reset-password'
    | '/terminos'
    | '/welcome'
    | '/achievements'
    | '/activity'
    | '/calendar'
    | '/charts'
    | '/dashboard'
    | '/export'
    | '/fasting'
    | '/goals'
    | '/habits'
    | '/history'
    | '/imc'
    | '/insights'
    | '/measurements'
    | '/more'
    | '/nutrition'
    | '/profile'
    | '/settings'
    | '/statistics'
    | '/support'
    | '/weekly-summary'
    | '/guias/$slug'
    | '/guias'
    | '/pricing/success'
    | '/api/auth/$'
    | '/pricing'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/calculadora-imc'
    | '/calculadora-peso-meta'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reembolsos'
    | '/register'
    | '/reset-password'
    | '/terminos'
    | '/welcome'
    | '/_authenticated/achievements'
    | '/_authenticated/activity'
    | '/_authenticated/calendar'
    | '/_authenticated/charts'
    | '/_authenticated/dashboard'
    | '/_authenticated/export'
    | '/_authenticated/fasting'
    | '/_authenticated/goals'
    | '/_authenticated/habits'
    | '/_authenticated/history'
    | '/_authenticated/imc'
    | '/_authenticated/insights'
    | '/_authenticated/measurements'
    | '/_authenticated/more'
    | '/_authenticated/nutrition'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/statistics'
    | '/_authenticated/support'
    | '/_authenticated/weekly-summary'
    | '/guias/$slug'
    | '/guias/'
    | '/_authenticated/pricing/success'
    | '/api/auth/$'
    | '/_authenticated/pricing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CalculadoraImcRoute: typeof CalculadoraImcRoute
  CalculadoraPesoMetaRoute: typeof CalculadoraPesoMetaRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ReembolsosRoute: typeof ReembolsosRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TerminosRoute: typeof TerminosRoute
  WelcomeRoute: typeof WelcomeRoute
  GuiasSlugRoute: typeof GuiasSlugRoute
  GuiasIndexRoute: typeof GuiasIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-imc': {
      id: '/calculadora-imc'
      path: '/calculadora-imc'
      fullPath: '/calculadora-imc'
      preLoaderRoute: typeof CalculadoraImcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-peso-meta': {
      id: '/calculadora-peso-meta'
      path: '/calculadora-peso-meta'
      fullPath: '/calculadora-peso-meta'
      preLoaderRoute: typeof CalculadoraPesoMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reembolsos': {
      id: '/reembolsos'
      path: '/reembolsos'
      fullPath: '/reembolsos'
      preLoaderRoute: typeof ReembolsosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/charts': {
      id: '/_authenticated/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof AuthenticatedChartsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/export': {
      id: '/_authenticated/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AuthenticatedExportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fasting': {
      id: '/_authenticated/fasting'
      path: '/fasting'
      fullPath: '/fasting'
      preLoaderRoute: typeof AuthenticatedFastingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/habits': {
      id: '/_authenticated/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof AuthenticatedHabitsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/imc': {
      id: '/_authenticated/imc'
      path: '/imc'
      fullPath: '/imc'
      preLoaderRoute: typeof AuthenticatedImcRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/measurements': {
      id: '/_authenticated/measurements'
      path: '/measurements'
      fullPath: '/measurements'
      preLoaderRoute: typeof AuthenticatedMeasurementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/more': {
      id: '/_authenticated/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AuthenticatedMoreRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nutrition': {
      id: '/_authenticated/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof AuthenticatedNutritionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/statistics': {
      id: '/_authenticated/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof AuthenticatedStatisticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/weekly-summary': {
      id: '/_authenticated/weekly-summary'
      path: '/weekly-summary'
      fullPath: '/weekly-summary'
      preLoaderRoute: typeof AuthenticatedWeeklySummaryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/guias/': {
      id: '/guias/'
      path: '/guias'
      fullPath: '/guias/'
      preLoaderRoute: typeof GuiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guias/$slug': {
      id: '/guias/$slug'
      path: '/guias/$slug'
      fullPath: '/guias/$slug'
      preLoaderRoute: typeof GuiasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pricing/': {
      id: '/_authenticated/pricing/'
      path: '/pricing'
      fullPath: '/pricing/'
      preLoaderRoute: typeof AuthenticatedPricingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pricing/success': {
      id: '/_authenticated/pricing/success'
      path: '/pricing/success'
      fullPath: '/pricing/success'
      preLoaderRoute: typeof AuthenticatedPricingSuccessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedChartsRoute: typeof AuthenticatedChartsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExportRoute: typeof AuthenticatedExportRoute
  AuthenticatedFastingRoute: typeof AuthenticatedFastingRoute
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRoute
  AuthenticatedHabitsRoute: typeof AuthenticatedHabitsRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedImcRoute: typeof AuthenticatedImcRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedMeasurementsRoute: typeof AuthenticatedMeasurementsRoute
  AuthenticatedMoreRoute: typeof AuthenticatedMoreRoute
  AuthenticatedNutritionRoute: typeof AuthenticatedNutritionRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStatisticsRoute: typeof AuthenticatedStatisticsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedWeeklySummaryRoute: typeof AuthenticatedWeeklySummaryRoute
  AuthenticatedPricingSuccessRoute: typeof AuthenticatedPricingSuccessRoute
  AuthenticatedPricingIndexRoute: typeof AuthenticatedPricingIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedChartsRoute: AuthenticatedChartsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExportRoute: AuthenticatedExportRoute,
  AuthenticatedFastingRoute: AuthenticatedFastingRoute,
  AuthenticatedGoalsRoute: AuthenticatedGoalsRoute,
  AuthenticatedHabitsRoute: AuthenticatedHabitsRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedImcRoute: AuthenticatedImcRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedMeasurementsRoute: AuthenticatedMeasurementsRoute,
  AuthenticatedMoreRoute: AuthenticatedMoreRoute,
  AuthenticatedNutritionRoute: AuthenticatedNutritionRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStatisticsRoute: AuthenticatedStatisticsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedWeeklySummaryRoute: AuthenticatedWeeklySummaryRoute,
  AuthenticatedPricingSuccessRoute: AuthenticatedPricingSuccessRoute,
  AuthenticatedPricingIndexRoute: AuthenticatedPricingIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CalculadoraImcRoute: CalculadoraImcRoute,
  CalculadoraPesoMetaRoute: CalculadoraPesoMetaRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ReembolsosRoute: ReembolsosRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TerminosRoute: TerminosRoute,
  WelcomeRoute: WelcomeRoute,
  GuiasSlugRoute: GuiasSlugRoute,
  GuiasIndexRoute: GuiasIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
